# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - veterinaria-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ AZUREAPPSERVICE_CLIENTID_475F93918E3B45F1AF4E4E488DF9A19E }}
          tenant-id: ${{ AZUREAPPSERVICE_TENANTID_B2CAE2F086A842949C3EC9950364FDDF }}
          subscription-id: ${{ AZUREAPPSERVICE_SUBSCRIPTIONID_A792FB2A67404A0287299D168D1AD3A5}}


      - name: Build (if necessary)
        working-directory: ./backend
        run: npm run build --if-present

      - name: Test (if necessary)
        working-directory: ./backend
        run: npm test --if-present

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: veterinaria-backend
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./backend